In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 00. Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

In [3]:
# Creating tensors
# Scalar
# PyTorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Scalar**: 0 dimentional tensor

**Vector**: 1 dimentional tensor

**Matrix**: 2 dimentional tensor

**Tensor**: n dimentions

# **Random Tensors**
Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [18]:
# Create a random tensor with pytorch
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.2230, 0.5973, 0.4862, 0.9041, 0.1324, 0.3433, 0.0169, 0.9140, 0.8709,
         0.9527],
        [0.0825, 0.7384, 0.7976, 0.8648, 0.4032, 0.3553, 0.9718, 0.4984, 0.9904,
         0.1085],
        [0.1988, 0.6847, 0.5483, 0.8532, 0.5581, 0.6230, 0.8908, 0.7421, 0.3235,
         0.3322],
        [0.1004, 0.4885, 0.5414, 0.4732, 0.5025, 0.6891, 0.3874, 0.2043, 0.5362,
         0.3833],
        [0.8960, 0.3114, 0.0019, 0.2917, 0.6496, 0.9825, 0.6429, 0.1150, 0.2348,
         0.7325],
        [0.5466, 0.5355, 0.8413, 0.4078, 0.6248, 0.3832, 0.7700, 0.1184, 0.6330,
         0.8504],
        [0.7469, 0.8112, 0.3164, 0.1389, 0.3494, 0.7154, 0.6293, 0.2822, 0.1666,
         0.8507],
        [0.8670, 0.7827, 0.6556, 0.1801, 0.0701, 0.5953, 0.6850, 0.8435, 0.1652,
         0.0951],
        [0.6172, 0.6482, 0.3565, 0.6905, 0.1700, 0.5271, 0.1466, 0.6417, 0.1945,
         0.0278],
        [0.0067, 0.1256, 0.7638, 0.4144, 0.6228, 0.6787, 0.7464, 0.4714, 0.9221,
         0.8333]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, color channels(R,G,B)

In [21]:
random_image_size_tensor


tensor([[[0.9730, 0.9501, 0.1745,  ..., 0.9639, 0.7990, 0.0946],
         [0.0619, 0.4933, 0.5802,  ..., 0.9862, 0.2501, 0.8353],
         [0.4019, 0.8582, 0.1605,  ..., 0.9929, 0.1876, 0.9317],
         ...,
         [0.3586, 0.8199, 0.4075,  ..., 0.9194, 0.4661, 0.4063],
         [0.8293, 0.3327, 0.6574,  ..., 0.9564, 0.2512, 0.9425],
         [0.1937, 0.5817, 0.5128,  ..., 0.4480, 0.9560, 0.1005]],

        [[0.5613, 0.0535, 0.8437,  ..., 0.0975, 0.4132, 0.5780],
         [0.0162, 0.2094, 0.1672,  ..., 0.4944, 0.0737, 0.1839],
         [0.9643, 0.5290, 0.7296,  ..., 0.1966, 0.0350, 0.1440],
         ...,
         [0.9997, 0.4343, 0.2910,  ..., 0.1942, 0.8528, 0.7330],
         [0.0905, 0.8297, 0.0799,  ..., 0.7465, 0.9879, 0.7859],
         [0.4998, 0.7172, 0.1158,  ..., 0.3656, 0.6050, 0.7923]],

        [[0.1738, 0.8061, 0.6104,  ..., 0.9616, 0.5192, 0.5448],
         [0.5714, 0.6221, 0.1120,  ..., 0.1778, 0.6060, 0.0140],
         [0.3787, 0.8079, 0.3259,  ..., 0.2975, 0.9556, 0.

In [22]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [23]:
random_image_size_tensor.ndim


3

# **Zeros and ones**

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(10,10))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
# create a tensor of all ones
ones= torch.ones(size=(10,10))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like


In [29]:
# use torch.range
torch.range(0,10)

<ipython-input-29-255291c05083>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
zero_to_thousand = torch.arange(start=0, end=1000, step=77)
zero_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

Creating tensors like

In [33]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# ***Tensor Datatypes***
**Note:** Tensor datatypes is one of the 3 big errors you'll run into PyTorch & deep learning

1. Tensors not right datatype
2.Tensors not right shape
3. Tensors not on the right device


In [34]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (eg, float 32 or float 16)
                              #  device = "cuda",#what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

# **Getting information from tensors**

1. Tensors not right datatype -> to do get datatype from a tensor, can use tensor.dtype
2.Tensors not right shape -> to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device -> to get device from a tensor, can use tensor.device



In [40]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor



tensor([[0.7725, 0.6479, 0.7361, 0.3730],
        [0.8259, 0.9541, 0.4224, 0.7167],
        [0.4885, 0.5591, 0.6682, 0.7771]])

In [41]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7725, 0.6479, 0.7361, 0.3730],
        [0.8259, 0.9541, 0.4224, 0.7167],
        [0.4885, 0.5591, 0.6682, 0.7771]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors (Tensor operations)

1.   Addition
2.   Subtraction
3. Multiplication (Elementwise)
4. Division
5. Matrix Multiplication



In [42]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [43]:
# adding 10 to a tensor
tensor + 10

tensor([11, 12, 13])

In [44]:
# multiply a tensor by 10
tensor*10

tensor([10, 20, 30])

In [45]:
# try out pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix Multiplication
2 main ways in DL
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match

* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [47]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))
# won't work

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))
# will work

tensor([[0.2395, 0.3188, 0.6682],
        [0.1927, 0.2943, 0.4925],
        [0.1147, 0.1450, 0.3291]])

In [49]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
# Matrix Multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 833 µs, sys: 0 ns, total: 833 µs
Wall time: 794 µs


tensor(14)

In [51]:
tensor

tensor([1, 2, 3])

In [52]:
# Matrix Multiplication by hand
%%time
1*1 + 2*2 + 3*3

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs


14

In [53]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.9 ms, sys: 21 µs, total: 1.92 ms
Wall time: 2.19 ms


# One of the most common errors in deep learning: shape errors

# Finding the min, max, mean, sum, etc (Tensor aggregation)

In [54]:
tensor = torch.tensor([[27,30,33],
                       [61,68,75],
                       [95,106,117]])
tensor

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
# or create a tensor by range
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# find the minimum
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
# find the maximum
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
# finding mean
torch.mean(x)
# it will show error cz it's not float or complex

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [59]:
x.dtype

torch.int64

In [60]:
# Note: The torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# **Finding positional min and max**

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [64]:
x[0]

tensor(0)

In [65]:
x[1]

tensor(10)

In [66]:
# find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where the minimum value occurs
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(90)

# Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [72]:
# let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
# add an extra dimension
# reshape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

Before reshaping, the torch size was 9.
9 * 1 = 1 * 9 = 9



In [77]:
y = torch.arange(1.,13.)
y

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [78]:
y_reshaped = y.reshape(3,4)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [79]:
y_reshaped = y.reshape(4,3)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [80]:
y_reshaped = y.reshape(2,6)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [81]:
y_reshaped = y.reshape(6,2)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [84]:
# change the view
# view does quite the similar job as reshape
# although, it shares the same memory of the original tensor
z = y.view(2,6)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [85]:
# changing z changes y (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5

z,y

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.],
         [ 5.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  5.,  8.,  9., 10., 11., 12.]))

# Stack tensors on top of each other

In [90]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

# torch.squeeze( ) - removes all single dimensions from a target tensor


In [103]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [99]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [100]:
x_reshaped.shape

torch.Size([1, 9])

In [101]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [102]:
x_reshaped.squeeze().shape

torch.Size([9])

In [104]:
# after squeezing
print(f"New tensor: {x_reshaped.squeeze()}")
print(f"New shape: {x_reshaped.squeeze().shape}")

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


# torch.unsqueeze( ) - > adds a single dimension to a target tensor at a specific dim

In [105]:
print(f"Previous tensor: {x_reshaped.squeeze()}")
print(f"Previous shape: {x_reshaped.squeeze().shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])


In [108]:
# Add an extra dimension:
x_unsqueezed = x_reshaped.squeeze().unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


# torch.permute - rearranges the dimensions of a target tensor in a specified order


In [114]:
x_original = torch.rand(size=(224,325,3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
# [color channels, height, width]

Previous shape: torch.Size([224, 325, 3])
New shape: torch.Size([3, 224, 325])


In [115]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]


(tensor(728218.), tensor(728218.))

# indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [121]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

let's index on our new tensor

In [122]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

let's index on the middle bracket (dim=1)

In [125]:
x[0][0]
# or x[0,0]


tensor([1, 2, 3])

In [128]:
x[0][1]

tensor([4, 5, 6])

let's index on the most inner bracket (last dimension)

In [126]:
x[0][0][0]

tensor(1)

In [127]:
x[0][0][1]

tensor(2)

In [132]:
x[0][2][2]

tensor(9)

we can also use ":" to select "all" of a target dimension

In [133]:
x[:,0]

tensor([[1, 2, 3]])

In [134]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [135]:
# to return 9:
x[:,2,2]

tensor([9])

In [136]:
# to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

# **Pytorch tensors and Numpy**

* NumPy to Pytorch tensor - > `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy - > `torch.Tensor.numpy()`

In [143]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [146]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [148]:
# if we change values of the numpy array, what will this do to the tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

# Tensor to NumPy array

In [151]:
tensor  = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [152]:
# what happens to the numpy array if we change the tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# **Reproducibility** (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of **Random Seed**

Essentially what the random seed does is "flavour" the randomness




In [156]:
torch.rand(3,3)

tensor([[0.3777, 0.3957, 0.2286],
        [0.9057, 0.5563, 0.4053],
        [0.4671, 0.9673, 0.3602]])

In [168]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8852, 0.9501, 0.8587, 0.4796],
        [0.7885, 0.1063, 0.2154, 0.7309],
        [0.3612, 0.6445, 0.3202, 0.1250]])
tensor([[0.9723, 0.1462, 0.5688, 0.4936],
        [0.3634, 0.0409, 0.6703, 0.2477],
        [0.8069, 0.6743, 0.4017, 0.5457]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [186]:
# Let's make some random but reproducible tensors
import torch
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# **Accessing a GPU**
GPU = faster computation on numbers

In [3]:
# check for gpu access with pytorch

import torch
torch.cuda.is_available()

True

In [4]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count the numbers of gpus
torch.cuda.device_count()

1

# Putting tensors and models on the gpu



In [6]:
# create a tensor (default on cpu)
tensor = torch.tensor([1,2,3],device="cpu")

# tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# move tensors back to the cpu


In [8]:
# if tensor in on gpu, can't transform it to numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# to fix the GPU tensor with numpy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy(), tensor_back_on_cpu.device

(array([1, 2, 3]), device(type='cpu'))